const mongoose = require("mongoose");
const db = require("../models");
// This file empties the Books collection and inserts the books below
mongoose.connect(
  process.env.MONGODB_URI ||
  "mongodb://localhost/podCastDB"
);
const podcastSeed = [
  
    {
      "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
      "description_highlighted": "...My <span class=\"ln-search-highlight\">Star</span> <span class=\"ln-search-highlight\">Wars</span> Story is a project to document the impact of <span class=\"ln-search-highlight\">Star</span> <span class=\"ln-search-highlight\">Wars</span> on the lives of those in the <span class=\"ln-search-highlight\">Star</span> <span class=\"ln-search-highlight\">Wars</span> Generation. We're looking to tell as many people's stories as possible.",
      "description_original": "My Star Wars Story is a project to document the impact of Star Wars on the lives of those in the Star Wars Generation. We're looking to tell as many people's stories as possible.  If you'd like to tell your Star Wars Story, please send an email to story@mystarwarsstory.com",
      "title_highlighted": "My <span class=\"ln-search-highlight\">Star</span> <span class=\"ln-search-highlight\">Wars</span> Story",
      "title_original": "My Star Wars Story",
      "publisher_highlighted": "Scott Ryfun Talk Entertainment",
      "publisher_original": "Scott Ryfun Talk Entertainment",
      "image": "https://production.listennotes.com/podcasts/my-star-wars-story-scott-ryfun-talk--INHBbhEorW-eDiGl0J52_H.300x214.jpg",
      "thumbnail": "https://production.listennotes.com/podcasts/my-star-wars-story-scott-ryfun-talk--INHBbhEorW-eDiGl0J52_H.300x214.jpg",
      "itunes_id": 913296172,
      "latest_pub_date_ms": 1577426973000,
      "earliest_pub_date_ms": 1409166393038,
      "id": "8d2fa21d479e4500bdf4bf7e4183ec66",
      "genre_ids": [
          68
      ],
      "listennotes_url": "https://www.listennotes.com/c/8d2fa21d479e4500bdf4bf7e4183ec66/",
      "total_episodes": 39,
      "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
      "explicit_content": false,
      "website": "http://mystarwarsstory.libsyn.com/webpage?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
      "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
      "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
  },
  {
      "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
      "description_highlighted": "...to re-watches of classic <span class=\"ln-search-highlight\">Star</span> <span class=\"ln-search-highlight\">Wars</span> titles.",
      "description_original": "A podcast about a galaxy, far, far away: Entertainment Weekly reporter James Hibberd and critic Darren Franich discuss the latest Star Wars projects and news -- from The Rise of Skywalker to The Mandalorian to re-watches of classic Star Wars titles. Subscribe today, it’s not a trap!",
      "title_highlighted": "<span class=\"ln-search-highlight\">Star</span> <span class=\"ln-search-highlight\">Wars</span> Untold Stories",
      "title_original": "Star Wars Untold Stories",
      "publisher_highlighted": "Entertainment Weekly",
      "publisher_original": "Entertainment Weekly",
      "image": "https://production.listennotes.com/podcasts/star-wars-untold-stories-6khgK_zwvL9-7jJ42OxHr1k.300x300.jpg",
      "thumbnail": "https://production.listennotes.com/podcasts/star-wars-untold-stories-6khgK_zwvL9-7jJ42OxHr1k.300x300.jpg",
      "itunes_id": 1487489835,
      "latest_pub_date_ms": 1576803600000,
      "earliest_pub_date_ms": 1573490304006,
      "id": "0ffb3427aae748ce81416e2bc4a4b309",
      "genre_ids": [
          99,
          264,
          68,
          214
      ],
      "listennotes_url": "https://www.listennotes.com/c/0ffb3427aae748ce81416e2bc4a4b309/",
      "total_episodes": 7,
      "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
      "explicit_content": false,
      "website": "https://ew.com/?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
      "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
      "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
  },
  {
      "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
      "description_highlighted": "...Though we cover a variety of subjects within TV and film, we focus on commentary and analysis of the ever growing <span class=\"ln-search-highlight\">Star</span> <span class=\"ln-search-highlight\">Wars</span> universe.",
      "description_original": "Who Talks First is a weekly podcast hosted by CT and Solo of the Youtube Channel KnightsofRant.  Two humans who like things too much, and spend too much time raving (and ranting) about them.  Though we cover a variety of subjects within TV and film, we focus on commentary and analysis of the ever growing Star Wars universe.",
      "title_highlighted": "Who Talks First: A Mostly <span class=\"ln-search-highlight\">Star</span> <span class=\"ln-search-highlight\">Wars</span> Podcast",
      "title_original": "Who Talks First: A Mostly Star Wars Podcast",
      "publisher_highlighted": "Knights of Rant",
      "publisher_original": "Knights of Rant",
      "image": "https://production.listennotes.com/podcasts/who-talks-first-a-mostly-star-wars-podcast-4d0NJoGhu6E.300x300.jpg",
      "thumbnail": "https://production.listennotes.com/podcasts/who-talks-first-a-mostly-star-wars-podcast-4d0NJoGhu6E.300x300.jpg",
      "itunes_id": 1198046920,
      "latest_pub_date_ms": 1578374762000,
      "earliest_pub_date_ms": 1485118415085,
      "id": "1800b288804240ed8a7833db8cb98805",
      "genre_ids": [
          68
      ],
      "listennotes_url": "https://www.listennotes.com/c/1800b288804240ed8a7833db8cb98805/",
      "total_episodes": 69,
      "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
      "explicit_content": false,
      "website": "https://www.etsy.com/shop/squadrongoals?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
      "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
      "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
  },
  {
      "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
      "description_highlighted": "...<span class=\"ln-search-highlight\">Star</span> Scavengers is a podcast hosted by Johnamarie Macias and Aaron Goins covering all things LEGO <span class=\"ln-search-highlight\">Star</span> <span class=\"ln-search-highlight\">Wars</span>.",
      "description_original": "Star Scavengers is a podcast hosted by Johnamarie Macias and Aaron Goins covering all things LEGO Star Wars. Expect reviews of the Freemaker Adventures animated series, fun guests, informative interviews, and even some discussion on collecting.",
      "title_highlighted": "<span class=\"ln-search-highlight\">Star</span> Scavengers: A LEGO <span class=\"ln-search-highlight\">Star</span> <span class=\"ln-search-highlight\">Wars</span> Podcast",
      "title_original": "Star Scavengers: A LEGO Star Wars Podcast",
      "publisher_highlighted": "LEGO Star Wars",
      "publisher_original": "LEGO Star Wars",
      "image": "https://production.listennotes.com/podcasts/star-scavengers-a-lego-star-wars-podcast-CL82adZ-UM1-zk-eNup0HPd.300x300.jpg",
      "thumbnail": "https://production.listennotes.com/podcasts/star-scavengers-a-lego-star-wars-podcast-CL82adZ-UM1-zk-eNup0HPd.300x300.jpg",
      "itunes_id": 1129608040,
      "latest_pub_date_ms": 1577834040000,
      "earliest_pub_date_ms": 1467177840036,
      "id": "f96d499273d2459e98e29df7f359c01f",
      "genre_ids": [
          86,
          68,
          82
      ],
      "listennotes_url": "https://www.listennotes.com/c/f96d499273d2459e98e29df7f359c01f/",
      "total_episodes": 37,
      "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
      "explicit_content": false,
      "website": "http://www.starscavengers.com?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
      "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
      "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
  },
  {
      "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
      "description_highlighted": "...Greetings! Thanks for checking out this show, hosted by me, Darth Podcast. Tune in for discussions, reviews, news, theories, and more. We would be honored.. if you would join us. ",
      "description_original": "Greetings! Thanks for checking out this show, hosted by me, Darth Podcast. Tune in for discussions, reviews, news, theories, and more. We would be honored.. if you would join us. ",
      "title_highlighted": "<span class=\"ln-search-highlight\">Star</span> <span class=\"ln-search-highlight\">Wars</span>: Darth Podcast",
      "title_original": "Star Wars: Darth Podcast",
      "publisher_highlighted": "Cade Ellsworth",
      "publisher_original": "Cade Ellsworth",
      "image": "https://production.listennotes.com/podcasts/star-wars-darth-podcast-cade-ellsworth-wdu4PEf2WKT-ZMeSpQ_RfPx.300x300.jpg",
      "thumbnail": "https://production.listennotes.com/podcasts/star-wars-darth-podcast-cade-ellsworth-wdu4PEf2WKT-ZMeSpQ_RfPx.300x300.jpg",
      "itunes_id": 1439745642,
      "latest_pub_date_ms": 1576652400000,
      "earliest_pub_date_ms": 1540094400033,
      "id": "80cac44351494350bd22caf44a6faa1d",
      "genre_ids": [
          168,
          68,
          185
      ],
      "listennotes_url": "https://www.listennotes.com/c/80cac44351494350bd22caf44a6faa1d/",
      "total_episodes": 34,
      "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
      "explicit_content": false,
      "website": null,
      "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
      "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
  },
  {
      "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
      "description_highlighted": "...Listen to your new favorite podcast dedicated to <span class=\"ln-search-highlight\">Star</span> <span class=\"ln-search-highlight\">Wars</span> Destiny from Fantasy Flight Games.  Join Mr.",
      "description_original": "Stop playing that trash, coach!  Listen to your new favorite podcast dedicated to Star Wars Destiny from Fantasy Flight Games.  Join Mr. Chip, a washed-up former professional podcaster and wanna-be competitive player, and Jay, who has played more trash decks on Tabletop Simulator than one person should be allowed to - as they work together to make for an entertaining show you won't soon forget.  Join our patreon at discardtoreroll.com and become a part of the DB family!",
      "title_highlighted": "Discard to Reroll - <span class=\"ln-search-highlight\">Star</span> <span class=\"ln-search-highlight\">Wars</span> Destiny",
      "title_original": "Discard to Reroll - Star Wars Destiny",
      "publisher_highlighted": "Discard to Reroll",
      "publisher_original": "Discard to Reroll",
      "image": "https://production.listennotes.com/podcasts/discard-to-reroll-star-wars-destiny-discard-Ck4VmTWetJS-LabJ0gNnpwz.300x300.jpg",
      "thumbnail": "https://production.listennotes.com/podcasts/discard-to-reroll-star-wars-destiny-discard-Ck4VmTWetJS-LabJ0gNnpwz.300x300.jpg",
      "itunes_id": 1316865564,
      "latest_pub_date_ms": 1579692595000,
      "earliest_pub_date_ms": 1572520417002,
      "id": "9de3c20bd9834f25b9f9560d1125d3c8",
      "genre_ids": [
          85,
          82
      ],
      "listennotes_url": "https://www.listennotes.com/c/9de3c20bd9834f25b9f9560d1125d3c8/",
      "total_episodes": 3,
      "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
      "explicit_content": false,
      "website": "https://www.spreaker.com/show/discard2reroll?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
      "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
      "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
  },
  {
      "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
      "description_highlighted": "...A weekly show featuring news and insight into everything <span class=\"ln-search-highlight\">Star</span> <span class=\"ln-search-highlight\">Wars</span>.  Hosted by Alex Maxwell and Mac Lacey, the show covers everything old and new in the <span class=\"ln-search-highlight\">Star</span> <span class=\"ln-search-highlight\">Wars</span> universe. Email us!",
      "description_original": "A weekly show featuring news and insight into everything Star Wars.  Hosted by Alex Maxwell and Mac Lacey, the show covers everything old and new in the Star Wars universe. Email us! swescapepod@gmail.com",
      "title_highlighted": "The <span class=\"ln-search-highlight\">Star</span> <span class=\"ln-search-highlight\">Wars</span> Escape Podcast",
      "title_original": "The Star Wars Escape Podcast",
      "publisher_highlighted": "Star Wars (The Star Wars Escape Podcast)",
      "publisher_original": "Star Wars (The Star Wars Escape Podcast)",
      "image": "https://production.listennotes.com/podcasts/the-star-wars-escape-podcast-star-wars-the-pnZhEt-o4sD-qSzNDTrFhWA.300x300.jpg",
      "thumbnail": "https://production.listennotes.com/podcasts/the-star-wars-escape-podcast-star-wars-the-pnZhEt-o4sD-qSzNDTrFhWA.300x300.jpg",
      "itunes_id": 1294038398,
      "latest_pub_date_ms": 1558422000000,
      "earliest_pub_date_ms": 1507359600063,
      "id": "5978a93c01394f0ba3f24fdb8fe80fad",
      "genre_ids": [
          68
      ],
      "listennotes_url": "https://www.listennotes.com/c/5978a93c01394f0ba3f24fdb8fe80fad/",
      "total_episodes": 64,
      "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
      "explicit_content": false,
      "website": "http://www.podcastgarden.com/podcast/swescapepod?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website#13222",
      "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
      "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
  },
  {
      "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
      "description_highlighted": "...This fall, story expert Alastair Stephens will look at each of the six core <span class=\"ln-search-highlight\">Star</span> <span class=\"ln-search-highlight\">Wars</span> movies in release order, and analyse what works and why.",
      "description_original": "This fall, story expert Alastair Stephens will look at each of the six core Star Wars movies in release order, and analyse what works and why. We’re going to talk about heroic motivations, serial structure, the power of the five-man band, the interaction of intent and execution, mythic archetypes, the urge to explain, and stories which grow in the telling — and perhaps, we’ll understand a little better why Star Wars is the most important pop culture phenomenon of the modern era.",
      "title_highlighted": "Story and <span class=\"ln-search-highlight\">Star</span> <span class=\"ln-search-highlight\">Wars</span>",
      "title_original": "Story and Star Wars",
      "publisher_highlighted": "Point North Media",
      "publisher_original": "Point North Media",
      "image": "https://production.listennotes.com/podcasts/story-and-star-wars-point-north-media-t_cvksqYpjg.300x300.jpg",
      "thumbnail": "https://production.listennotes.com/podcasts/story-and-star-wars-point-north-media-t_cvksqYpjg.300x300.jpg",
      "itunes_id": 1041484891,
      "latest_pub_date_ms": 1528573253000,
      "earliest_pub_date_ms": 1442577656000,
      "id": "220fa67a4ef847ddbbcdda44a0c333f8",
      "genre_ids": [
          68,
          100,
          104,
          111,
          122,
          160,
          138
      ],
      "listennotes_url": "https://www.listennotes.com/c/220fa67a4ef847ddbbcdda44a0c333f8/",
      "total_episodes": 16,
      "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
      "explicit_content": false,
      "website": "http://pointnorthmedia.com?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
      "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
      "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
  },
  {
      "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
      "description_highlighted": "...Fandalorians is a <span class=\"ln-search-highlight\">Star</span> <span class=\"ln-search-highlight\">Wars</span> podcast for a growing galaxy! Hosts Sean Gerber and John Bierly analyze all of the latest news for an ever-expanding canon.",
      "description_original": "Fandalorians is a Star Wars podcast for a growing galaxy! Hosts Sean Gerber and John Bierly analyze all of the latest news for an ever-expanding canon. Feature films, animation, comics, novels, and a new era of live-action series like The Mandalorian on Disney+ are all up for discussion.",
      "title_highlighted": "Fandalorians - A <span class=\"ln-search-highlight\">Star</span> <span class=\"ln-search-highlight\">Wars</span> Podcast for a Growing Galaxy",
      "title_original": "Fandalorians - A Star Wars Podcast for a Growing Galaxy",
      "publisher_highlighted": "Sean Gerber",
      "publisher_original": "Sean Gerber",
      "image": "https://production.listennotes.com/podcasts/fandalorians-a-star-wars-podcast-for-a-SgIOy2UCNxF-TOhovFw5YfP.300x300.jpg",
      "thumbnail": "https://production.listennotes.com/podcasts/fandalorians-a-star-wars-podcast-for-a-SgIOy2UCNxF-TOhovFw5YfP.300x300.jpg",
      "itunes_id": 1448278449,
      "latest_pub_date_ms": 1577923414000,
      "earliest_pub_date_ms": 1546480816027,
      "id": "1276bb4570414fa7bf83d05e5fc53650",
      "genre_ids": [
          68
      ],
      "listennotes_url": "https://www.listennotes.com/c/1276bb4570414fa7bf83d05e5fc53650/",
      "total_episodes": 28,
      "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
      "explicit_content": false,
      "website": "http://soundcloud.com/fandalorians?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
      "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
      "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
  },
  {
      "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
      "description_highlighted": "...The news based sister podcast to Steele <span class=\"ln-search-highlight\">Wars</span> : <span class=\"ln-search-highlight\">Star</span> <span class=\"ln-search-highlight\">Wars</span> podcast also available on iTunes or wherever podcasts are found.",
      "description_original": "The news based sister podcast to Steele Wars : Star Wars podcast also available on iTunes or wherever podcasts are found.\n\nAustralian comedian Steele Saunders runs through the week's Star Wars news and takes YOUR CALLS with a special guest each week.\n\nLISTEN LIVE AND PARTICIPATE IN THE STEELE WARS CALL IN SHOW\n\nSTREAMLIVE BlogTalkRadio.com/SteeleWars\nCALL IN (646) 668-8360 USA\nSKYPE IN +1 (646) 668-8360 WORLDWIDE",
      "title_highlighted": "Steele <span class=\"ln-search-highlight\">Wars</span> : Live <span class=\"ln-search-highlight\">Star</span> <span class=\"ln-search-highlight\">Wars</span> Call In Show",
      "title_original": "Steele Wars : Live Star Wars Call In Show",
      "publisher_highlighted": "Star Wars",
      "publisher_original": "Star Wars",
      "image": "https://production.listennotes.com/podcasts/steele-wars-live-star-wars-call-in-show-Wl8LZiav3CY-BHYwxqgJItK.300x300.jpg",
      "thumbnail": "https://production.listennotes.com/podcasts/steele-wars-live-star-wars-call-in-show-Wl8LZiav3CY-BHYwxqgJItK.300x300.jpg",
      "itunes_id": 1146099290,
      "latest_pub_date_ms": 1553364267000,
      "earliest_pub_date_ms": 1471950523063,
      "id": "6137998dbb8a4a9ea397f6a3e5678560",
      "genre_ids": [
          68,
          133,
          160,
          138
      ],
      "listennotes_url": "https://www.listennotes.com/c/6137998dbb8a4a9ea397f6a3e5678560/",
      "total_episodes": 64,
      "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
      "explicit_content": false,
      "website": "http://steelewars.com/?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
      "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
      "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
  },
  {
    "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
    "description_highlighted": "...Join Sky <span class=\"ln-search-highlight\">Sports</span> WWE Editor Jefferson Lake and the team as they delve into the world of <span class=\"ln-search-highlight\">Sports</span> Entertainment.",
    "description_original": "Join Sky Sports WWE Editor Jefferson Lake and the team as they delve into the world of Sports Entertainment. The Lock Up crew will be breaking down Raw and SmackDown plus all the latest news and topics from the world of WWE. We'll be chatting with the current crop of Superstars as well as stars from the past! So don't forget to rate, review and subscribe to Sky Sports Lock Up on iTunes.",
    "title_highlighted": "Sky <span class=\"ln-search-highlight\">Sports</span> Lock Up",
    "title_original": "Sky Sports Lock Up",
    "publisher_highlighted": "Sky Sports",
    "publisher_original": "Sky Sports",
    "image": "https://production.listennotes.com/podcasts/sky-sports-lock-up-sky-sports-4pdzyv-ruEj-axtN10YRBwg.300x300.jpg",
    "thumbnail": "https://production.listennotes.com/podcasts/sky-sports-lock-up-sky-sports-4pdzyv-ruEj-axtN10YRBwg.300x300.jpg",
    "itunes_id": 1355711985,
    "latest_pub_date_ms": 1576681175000,
    "earliest_pub_date_ms": 1520258612102,
    "id": "70f65b716c914dc38ed9155276ec1f36",
    "genre_ids": [
        77,
        78
    ],
    "listennotes_url": "https://www.listennotes.com/c/70f65b716c914dc38ed9155276ec1f36/",
    "total_episodes": 103,
    "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
    "explicit_content": false,
    "website": "https://www.spreaker.com/show/sky-sports-lock-up-wwe-podcast?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
    "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
    "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
},
{
    "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
    "description_highlighted": "...In the cut-throat world of <span class=\"ln-search-highlight\">sports</span> entrepreneurship, The <span class=\"ln-search-highlight\">Sports</span> Entrepreneur gives you the insights, tactics, and know-how to create a profitable <span class=\"ln-search-highlight\">sports</span> business.",
    "description_original": "In the cut-throat world of sports entrepreneurship, The Sports Entrepreneur gives you the insights, tactics, and know-how to create a profitable sports business. Through conversations with other sports entrepreneurs, business owners, coaches, and thought leaders you will learn what it takes to turn a passion for sports into your livelihood. \n\nCasey leads her listeners into the business of sports to uncover what it takes to be successful in creating, building, and expanding a sports-centric company. This show takes the sports-minded to the next level to become the sports entrepreneurs they want to be. If you want to leave a legacy for your family, turn your expertise into a system, grow your current company, learn the business of sports, or simply listen to successful entrepreneurs share their insights then The Sports Entrepreneur is for you.",
    "title_highlighted": "The <span class=\"ln-search-highlight\">Sports</span> Entrepreneur",
    "title_original": "The Sports Entrepreneur",
    "publisher_highlighted": "Casey Wright",
    "publisher_original": "Casey Wright",
    "image": "https://production.listennotes.com/podcasts/the-sports-entrepreneur-casey-wright-zTQVb7husKc-zv8HdhbtRw7.300x300.jpg",
    "thumbnail": "https://production.listennotes.com/podcasts/the-sports-entrepreneur-casey-wright-zTQVb7husKc-zv8HdhbtRw7.300x300.jpg",
    "itunes_id": 1436195394,
    "latest_pub_date_ms": 1578560400000,
    "earliest_pub_date_ms": 1540826752057,
    "id": "7a1a82228b554e469f820d47795bd82d",
    "genre_ids": [
        93,
        77
    ],
    "listennotes_url": "https://www.listennotes.com/c/7a1a82228b554e469f820d47795bd82d/",
    "total_episodes": 66,
    "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
    "explicit_content": false,
    "website": "https://www.thesportsentrepreneur.com?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
    "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
    "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
},
{
    "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
    "description_highlighted": "...I'll also be talking about <span class=\"ln-search-highlight\">sports</span> more generally, primarily the NFL.  Thank you so much and welcome to the Fantasy <span class=\"ln-search-highlight\">Sports</span> family, and I hope that you will start and continue listening.",
    "description_original": "Hey! I'm Vivek Iyer, the host of the Fantasy and Sports Podcast. What the show is all about is giving you all player to player fantasy football advice. I've noticed that many shows aren't year round, however I will be podcasting throughout the fantasy offseason and the regular season, usually once a week. I'll also be talking about sports more generally, primarily the NFL.  Thank you so much and welcome to the Fantasy Sports family, and I hope that you will start and continue listening.  \n\n",
    "title_highlighted": "Fantasy and <span class=\"ln-search-highlight\">Sports</span>",
    "title_original": "Fantasy and Sports",
    "publisher_highlighted": "Fantasy and Sports",
    "publisher_original": "Fantasy and Sports",
    "image": "https://production.listennotes.com/podcasts/fantasy-and-sports-fantasy-and-sports-Jqs7xwKZMdU-21h8qEC0Wvc.300x300.jpg",
    "thumbnail": "https://production.listennotes.com/podcasts/fantasy-and-sports-fantasy-and-sports-Jqs7xwKZMdU-21h8qEC0Wvc.300x300.jpg",
    "itunes_id": 1451375988,
    "latest_pub_date_ms": 1576909341000,
    "earliest_pub_date_ms": 1547958368034,
    "id": "a5be1495fa5545968fab8cca4b965174",
    "genre_ids": [
        77
    ],
    "listennotes_url": "https://www.listennotes.com/c/a5be1495fa5545968fab8cca4b965174/",
    "total_episodes": 39,
    "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
    "explicit_content": false,
    "website": "https://castbox.fm/ch/1984289?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
    "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
    "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
},
{
    "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
    "description_highlighted": "...Curt Schilling and Steve Deace are making <span class=\"ln-search-highlight\">sports</span> talk great again with one radical idea — <span class=\"ln-search-highlight\">sports</span> talk should be about … wait for it … <span class=\"ln-search-highlight\">sports</span>! Don't miss the aftershow with Curt's daily fantasy picks.",
    "description_original": "Curt Schilling and Steve Deace are making sports talk great again with one radical idea — sports talk should be about … wait for it … sports! Don't miss the aftershow with Curt's daily fantasy picks.",
    "title_highlighted": "We Talk <span class=\"ln-search-highlight\">Sports</span>",
    "title_original": "We Talk Sports",
    "publisher_highlighted": "Blaze Podcast Network",
    "publisher_original": "Blaze Podcast Network",
    "image": "https://production.listennotes.com/podcasts/we-talk-sports-vlJ5SL8ECzg-4q_fDEu38ym.300x300.jpg",
    "thumbnail": "https://production.listennotes.com/podcasts/we-talk-sports-vlJ5SL8ECzg-4q_fDEu38ym.300x300.jpg",
    "itunes_id": 1448405300,
    "latest_pub_date_ms": 1556907244000,
    "earliest_pub_date_ms": 1546545378077,
    "id": "fc3710195dff4168a71246774d7637d0",
    "genre_ids": [
        77
    ],
    "listennotes_url": "https://www.listennotes.com/c/fc3710195dff4168a71246774d7637d0/",
    "total_episodes": 78,
    "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
    "explicit_content": false,
    "website": "https://www.blazetv.com/?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
    "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
    "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
},
{
    "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
    "description_highlighted": "...Join Jim Litke and Tim Dahlberg for their newsy take on the week in <span class=\"ln-search-highlight\">sports</span>, backed by the shoe leather, insight, experience and worldwide reach of The Associated Press <span class=\"ln-search-highlight\">sports</span> department.",
    "description_original": "Join Jim Litke and Tim Dahlberg for their newsy take on the week in sports, backed by the shoe leather, insight, experience and worldwide reach of The Associated Press sports department. Over the last three decades, they've covered every major championship around the globe multiple times, so expect cameos from big names and guests drawn from the week's headlines.",
    "title_highlighted": "PodcastOne <span class=\"ln-search-highlight\">Sports</span> Now",
    "title_original": "PodcastOne Sports Now",
    "publisher_highlighted": "PodcastOne",
    "publisher_original": "PodcastOne",
    "image": "https://production.listennotes.com/podcasts/podcastone-sports-now-podcastone-vFX4KW5hbrs.300x300.jpg",
    "thumbnail": "https://production.listennotes.com/podcasts/podcastone-sports-now-podcastone-vFX4KW5hbrs.300x300.jpg",
    "itunes_id": 1332159149,
    "latest_pub_date_ms": 1566889200000,
    "earliest_pub_date_ms": 1515142800161,
    "id": "1899ce64c45c4ca8b597214c07c459e3",
    "genre_ids": [
        77,
        99,
        122
    ],
    "listennotes_url": "https://www.listennotes.com/c/1899ce64c45c4ca8b597214c07c459e3/",
    "total_episodes": 164,
    "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
    "explicit_content": false,
    "website": "https://www.podcastone.com/podcastone-sports-now?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
    "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
    "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
},
{
    "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
    "description_highlighted": "...Podcast by <span class=\"ln-search-highlight\">Sports</span> Buzz",
    "description_original": "Podcast by Sports Buzz",
    "title_highlighted": "<span class=\"ln-search-highlight\">Sports</span> Buzz",
    "title_original": "Sports Buzz",
    "publisher_highlighted": "Sports Buzz",
    "publisher_original": "Sports Buzz",
    "image": "https://production.listennotes.com/podcasts/sports-buzz-sports-buzz-iW0SwjqACrT-t1TwMUzy_ag.300x300.jpg",
    "thumbnail": "https://production.listennotes.com/podcasts/sports-buzz-sports-buzz-iW0SwjqACrT-t1TwMUzy_ag.300x300.jpg",
    "itunes_id": 1172534039,
    "latest_pub_date_ms": 1572513465000,
    "earliest_pub_date_ms": 1562725683002,
    "id": "67b1b0967f19463e9920c541ff7990c9",
    "genre_ids": [
        77
    ],
    "listennotes_url": "https://www.listennotes.com/c/67b1b0967f19463e9920c541ff7990c9/",
    "total_episodes": 3,
    "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
    "explicit_content": false,
    "website": "https://soundcloud.com/user-66871665?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
    "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
    "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
},
{
    "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
    "description_highlighted": "...The Good <span class=\"ln-search-highlight\">Sports</span> Podcast is dedicated to answering the big questions that surround sport, development, and all the different ways the two fields can interact: What does good look like?",
    "description_original": "The Good Sports Podcast is dedicated to answering the big questions that surround sport, development, and all the different ways the two fields can interact: What does good look like? How can we do better? And how can we measure it? We’re learning as we go – get involved, get talking, and get learning with us!",
    "title_highlighted": "The Good <span class=\"ln-search-highlight\">Sports</span> Podcast",
    "title_original": "The Good Sports Podcast",
    "publisher_highlighted": "The Good Sports",
    "publisher_original": "The Good Sports",
    "image": "https://production.listennotes.com/podcasts/the-good-sports-podcast-the-good-sports-ZKghqW2lNEL-HiJkNpwdv9C.300x300.jpg",
    "thumbnail": "https://production.listennotes.com/podcasts/the-good-sports-podcast-the-good-sports-ZKghqW2lNEL-HiJkNpwdv9C.300x300.jpg",
    "itunes_id": 1361332719,
    "latest_pub_date_ms": 1574146800000,
    "earliest_pub_date_ms": 1521492678023,
    "id": "80bd9da77bdc4d61a4bb782cf8aa6827",
    "genre_ids": [
        119,
        117
    ],
    "listennotes_url": "https://www.listennotes.com/c/80bd9da77bdc4d61a4bb782cf8aa6827/",
    "total_episodes": 24,
    "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
    "explicit_content": false,
    "website": "https://goodsportscast.org.uk?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
    "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
    "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
},
{
    "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
    "description_highlighted": "...<span class=\"ln-search-highlight\">Sports</span> news from your typical southeastern, American living room. Hosts: Will Mehall, Tyler Combs, and Jimmy Fanning. Producer: David Grayson",
    "description_original": "Sports news from your typical southeastern, American living room. Hosts: Will Mehall, Tyler Combs, and Jimmy Fanning. Producer: David Grayson",
    "title_highlighted": "American Pylon <span class=\"ln-search-highlight\">Sports</span> Radio",
    "title_original": "American Pylon Sports Radio",
    "publisher_highlighted": "David Grayson",
    "publisher_original": "David Grayson",
    "image": "https://production.listennotes.com/podcasts/american-pylon-sports-radio-david-grayson-wk9fZjFovuy-ExmsI3k2u6q.300x221.jpg",
    "thumbnail": "https://production.listennotes.com/podcasts/american-pylon-sports-radio-david-grayson-wk9fZjFovuy-ExmsI3k2u6q.300x221.jpg",
    "itunes_id": 1409455637,
    "latest_pub_date_ms": 1576030607000,
    "earliest_pub_date_ms": 1531085867046,
    "id": "1fe0881efce643808d4e1d1f659cc26a",
    "genre_ids": [
        99,
        80,
        77
    ],
    "listennotes_url": "https://www.listennotes.com/c/1fe0881efce643808d4e1d1f659cc26a/",
    "total_episodes": 47,
    "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
    "explicit_content": false,
    "website": "http://americanpylon.libsyn.com/website?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
    "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
    "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
},
{
    "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
    "description_highlighted": "...Discussions about <span class=\"ln-search-highlight\">sports</span> and society. Focusing on Indiana University athletics and college <span class=\"ln-search-highlight\">sports</span>.  Support this podcast: https://anchor.fm/brian-tonsoni/support",
    "description_original": "Discussions about sports and society. Focusing on Indiana University athletics and college sports.  Support this podcast: https://anchor.fm/brian-tonsoni/support",
    "title_highlighted": "<span class=\"ln-search-highlight\">Sports</span> Talk with Tonsoni",
    "title_original": "Sports Talk with Tonsoni",
    "publisher_highlighted": "Brian Tonsoni",
    "publisher_original": "Brian Tonsoni",
    "image": "https://production.listennotes.com/podcasts/sports-talk-with-tonsoni-brian-tonsoni-abWExv_zr-2-gEqUCOmlTBt.300x300.jpg",
    "thumbnail": "https://production.listennotes.com/podcasts/sports-talk-with-tonsoni-brian-tonsoni-abWExv_zr-2-gEqUCOmlTBt.300x300.jpg",
    "itunes_id": 1273290439,
    "latest_pub_date_ms": 1571275179000,
    "earliest_pub_date_ms": 1503068499124,
    "id": "31a2a7114b844e11b18509baec3de742",
    "genre_ids": [
        77
    ],
    "listennotes_url": "https://www.listennotes.com/c/31a2a7114b844e11b18509baec3de742/",
    "total_episodes": 125,
    "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
    "explicit_content": false,
    "website": null,
    "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
    "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
},
{
    "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
    "description_highlighted": "...Double Technical is a new <span class=\"ln-search-highlight\">Sports</span> Podcast! We talk everything Local <span class=\"ln-search-highlight\">Sports</span> including Kentucky, Bengals, Reds, FC Cincinnati and NKU to start each show, and then we talk about National News.",
    "description_original": "Double Technical is a new Sports Podcast! We talk everything Local Sports including Kentucky, Bengals, Reds, FC Cincinnati and NKU to start each show, and then we talk about National News. We want to have a platform for people to join in on the sports debate! Join in with your host Lucas Fryman every Monday and Friday! You can call/text us at (513) 788-1490! Join the Debate!  Support this podcast: https://anchor.fm/doubletechnical/support",
    "title_highlighted": "Double Technical: A <span class=\"ln-search-highlight\">Sports</span> Podcast",
    "title_original": "Double Technical: A Sports Podcast",
    "publisher_highlighted": "Double Technical",
    "publisher_original": "Double Technical",
    "image": "https://production.listennotes.com/podcasts/double-technical-a-sports-podcast-double-GXuJ8mKrM0x-CQ6WMKdgUhr.300x300.jpg",
    "thumbnail": "https://production.listennotes.com/podcasts/double-technical-a-sports-podcast-double-GXuJ8mKrM0x-CQ6WMKdgUhr.300x300.jpg",
    "itunes_id": 1355358711,
    "latest_pub_date_ms": 1558447200000,
    "earliest_pub_date_ms": 1519704175000,
    "id": "3cf26a7d6e6c437a8cc263d2210c46a4",
    "genre_ids": [
        77
    ],
    "listennotes_url": "https://www.listennotes.com/c/3cf26a7d6e6c437a8cc263d2210c46a4/",
    "total_episodes": 65,
    "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
    "explicit_content": false,
    "website": null,
    "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
    "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
},
{
  "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "description_highlighted": "...Bad TV may be a brain eating monster lurking in the dusty corners of your living room, but <span class=\"ln-search-highlight\">Television</span> Zombies are along for the fight!",
  "description_original": "Each week, Jeff, Tina, Paul and Zack discuss the latest news and happenings in the world of science fiction and fantasy television, as well as review new episodes of favorite (and hated) shows.  From Game of Thrones to Orphan Black, we look at the latest, greatest and lamest and give an irreverent view of new TV.  Bad TV may be a brain eating monster lurking in the dusty corners of your living room, but Television Zombies are along for the fight!",
  "title_highlighted": "<span class=\"ln-search-highlight\">Television</span> Zombies",
  "title_original": "Television Zombies",
  "publisher_highlighted": "Jeff, Tina, Paul and Zack",
  "publisher_original": "Jeff, Tina, Paul and Zack",
  "image": "https://production.listennotes.com/podcasts/television-zombies-jeff-tina-paul-and-zack-C6_8DEZog95.300x300.jpg",
  "thumbnail": "https://production.listennotes.com/podcasts/television-zombies-jeff-tina-paul-and-zack-C6_8DEZog95.300x300.jpg",
  "itunes_id": 260901899,
  "latest_pub_date_ms": 1558612800000,
  "earliest_pub_date_ms": 1248436800316,
  "id": "c884018b51c7413791e897e87bba7416",
  "genre_ids": [
      68
  ],
  "listennotes_url": "https://www.listennotes.com/c/c884018b51c7413791e897e87bba7416/",
  "total_episodes": 316,
  "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "explicit_content": true,
  "website": "http://www.televisionzombies.com?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
  "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
},
{
  "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "description_highlighted": "...Join Car Guy Extraordinaire Ron Reiling &amp; Pop Culture and Nostalgia Guy Mike Wilkerson as they review the best cars, trucks and vehicles that <span class=\"ln-search-highlight\">television</span> and movie history has to offer!",
  "description_original": "Join Car Guy Extraordinaire Ron Reiling &amp; Pop Culture and Nostalgia Guy Mike Wilkerson as they review the best cars, trucks and vehicles that television and movie history has to offer!",
  "title_highlighted": "2GuysTalkingCars – Fun, Nostalgia and Education About the Cars, Trucks and Vehicles from <span class=\"ln-search-highlight\">Television</span> & Movie History!",
  "title_original": "2GuysTalkingCars – Fun, Nostalgia and Education About the Cars, Trucks and Vehicles from Television & Movie History!",
  "publisher_highlighted": "Ron Reiling & Mike Wilkerson",
  "publisher_original": "Ron Reiling & Mike Wilkerson",
  "image": "https://production.listennotes.com/podcasts/2guystalkingcars-fun-nostalgia-and-aF6HM13g4oy-Ihl0Neatn9-.300x300.jpg",
  "thumbnail": "https://production.listennotes.com/podcasts/2guystalkingcars-fun-nostalgia-and-aF6HM13g4oy-Ihl0Neatn9-.300x300.jpg",
  "itunes_id": 1328557239,
  "latest_pub_date_ms": 1535413709000,
  "earliest_pub_date_ms": 1470098208000,
  "id": "bff1083776d244bda2e87f12a746c358",
  "genre_ids": [
      68
  ],
  "listennotes_url": "https://www.listennotes.com/c/bff1083776d244bda2e87f12a746c358/",
  "total_episodes": 5,
  "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "explicit_content": false,
  "website": "https://www.2gtdatacore.com/category/2guystalkingcars-fun-nostalgia-and-education-about-the-cars-trucks-and-vehicles-from-television-movie-history/?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
  "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
},
{
  "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "description_highlighted": "...Talking <span class=\"ln-search-highlight\">Television</span> with Jay and Chris is a podcast discussing great TV shows. Support this podcast: https://anchor.fm/talkingtelevision/support",
  "description_original": "Talking Television with Jay and Chris is a podcast discussing great TV shows. Support this podcast: https://anchor.fm/talkingtelevision/support",
  "title_highlighted": "Talking <span class=\"ln-search-highlight\">Television</span>",
  "title_original": "Talking Television",
  "publisher_highlighted": "Southport Media",
  "publisher_original": "Southport Media",
  "image": "https://production.listennotes.com/podcasts/talking-television-southport-media-sIO5cUeiVXJ-rX9miQb6-Ng.300x300.jpg",
  "thumbnail": "https://production.listennotes.com/podcasts/talking-television-southport-media-sIO5cUeiVXJ-rX9miQb6-Ng.300x300.jpg",
  "itunes_id": 1459014975,
  "latest_pub_date_ms": 1573002317000,
  "earliest_pub_date_ms": 1554613200032,
  "id": "79fcedc7a5da43babceb64923625e1b6",
  "genre_ids": [
      68
  ],
  "listennotes_url": "https://www.listennotes.com/c/79fcedc7a5da43babceb64923625e1b6/",
  "total_episodes": 33,
  "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "explicit_content": false,
  "website": "https://anchor.fm/talkingtelevision?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
  "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
},
{
  "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "description_highlighted": "...Welcome to Very Special <span class=\"ln-search-highlight\">Television</span>.",
  "description_original": "Ever watch a serious episode of a funny sitcom and wonder – \"What were they thinking?!?\" We sure as hell did! Join us each week as we watch and discuss the \"Very Special\" episodes of your favorite sitcoms from the 80s and 90s and tear them apart (and maybe learn a lesson or two in the process)! The Best Men: Chris, David, Jose, and Peter get their funny on with new weekly content  – for your listening pleasure. Welcome to Very Special Television.",
  "title_highlighted": "Very Special <span class=\"ln-search-highlight\">Television</span>",
  "title_original": "Very Special Television",
  "publisher_highlighted": "BestMen Media",
  "publisher_original": "BestMen Media",
  "image": "https://production.listennotes.com/podcasts/very-special-television-bestmen-media-rz5DfuPj9pk.300x300.jpg",
  "thumbnail": "https://production.listennotes.com/podcasts/very-special-television-bestmen-media-rz5DfuPj9pk.300x300.jpg",
  "itunes_id": 1210197243,
  "latest_pub_date_ms": 1538408069000,
  "earliest_pub_date_ms": 1486512653000,
  "id": "6486edd6fd2c42cfb178339b74d378da",
  "genre_ids": [
      133
  ],
  "listennotes_url": "https://www.listennotes.com/c/6486edd6fd2c42cfb178339b74d378da/",
  "total_episodes": 66,
  "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "explicit_content": true,
  "website": "http://soundcloud.com/bestmenpodcast?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
  "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
},
{
  "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "description_highlighted": "...A weekly recap of Once Upon A Time, a show where the subtext is domtext.",
  "description_original": "A weekly recap of Once Upon A Time, a show where the subtext is domtext.",
  "title_highlighted": "Welcome To Storybrooke - Welcome to <span class=\"ln-search-highlight\">Television</span>",
  "title_original": "Welcome To Storybrooke - Welcome to Television",
  "publisher_highlighted": "I Love Television Zines",
  "publisher_original": "I Love Television Zines",
  "image": "https://production.listennotes.com/podcasts/welcome-to-storybrooke-welcome-to-eIgb71LnEK2-3nTVBv-ielc.300x300.jpg",
  "thumbnail": "https://production.listennotes.com/podcasts/welcome-to-storybrooke-welcome-to-eIgb71LnEK2-3nTVBv-ielc.300x300.jpg",
  "itunes_id": 1153441122,
  "latest_pub_date_ms": 1571629778000,
  "earliest_pub_date_ms": 1473612149000,
  "id": "da81e0490b7649d5ac4264f488eab3cd",
  "genre_ids": [
      68
  ],
  "listennotes_url": "https://www.listennotes.com/c/da81e0490b7649d5ac4264f488eab3cd/",
  "total_episodes": 163,
  "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "explicit_content": true,
  "website": "http://www.ilovetelevisionzines.com/welcome-to-storybrook/?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
  "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
},
{
  "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "description_highlighted": "...Join Jedi Council hosts Ken Napzok, Emma Fyffe, and Ace Cabrera as they bring their unique experiences to the latest Star Wars news in movies, <span class=\"ln-search-highlight\">television</span>, comics, clothing, and more.",
  "description_original": "Our weekly reports from the Star Wars Universe! Join Jedi Council hosts Ken Napzok, Emma Fyffe, and Ace Cabrera as they bring their unique experiences to the latest Star Wars news in movies, television, comics, clothing, and more. Plus, speculate on the future of the franchise from the Sith perspective with Rule of Two.",
  "title_highlighted": "Collider Jedi Council",
  "title_original": "Collider Jedi Council",
  "publisher_highlighted": "PodcastOne",
  "publisher_original": "PodcastOne",
  "image": "https://production.listennotes.com/podcasts/collider-jedi-council-podcastone-6u_OYU2ey34-sQ5O9Br0Hia.300x300.jpg",
  "thumbnail": "https://production.listennotes.com/podcasts/collider-jedi-council-podcastone-6u_OYU2ey34-sQ5O9Br0Hia.300x300.jpg",
  "itunes_id": 1366420900,
  "latest_pub_date_ms": 1579248000000,
  "earliest_pub_date_ms": 1522389600166,
  "id": "8af29d07e16f47e38ef6fac147132f00",
  "genre_ids": [
      68,
      100,
      122,
      160,
      138
  ],
  "listennotes_url": "https://www.listennotes.com/c/8af29d07e16f47e38ef6fac147132f00/",
  "total_episodes": 167,
  "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "explicit_content": false,
  "website": "https://www.podcastone.com/collider-jedi-council?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
  "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
},
{
  "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "description_highlighted": "...Comedian Eric Schwartz interviews the best in comedy, music, film and <span class=\"ln-search-highlight\">television</span> and beyond, transforming their conversations into musicals. ",
  "description_original": "Comedian Eric Schwartz interviews the best in comedy, music, film and television and beyond, transforming their conversations into musicals. ",
  "title_highlighted": "Podcast: The Musical",
  "title_original": "Podcast: The Musical",
  "publisher_highlighted": "Eric Schwartz",
  "publisher_original": "Eric Schwartz",
  "image": "https://production.listennotes.com/podcasts/podcast-the-musical-e6kI8twa4sf-RXfLtMT1kFC.300x300.jpg",
  "thumbnail": "https://production.listennotes.com/podcasts/podcast-the-musical-e6kI8twa4sf-RXfLtMT1kFC.300x300.jpg",
  "itunes_id": 1489417668,
  "latest_pub_date_ms": 1578322800000,
  "earliest_pub_date_ms": 1574714607002,
  "id": "44357084c91046d7aed6c30674e1f46d",
  "genre_ids": [
      134,
      133,
      210,
      175
  ],
  "listennotes_url": "https://www.listennotes.com/c/44357084c91046d7aed6c30674e1f46d/",
  "total_episodes": 3,
  "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "explicit_content": false,
  "website": "http://podthemusical.libsyn.com/website?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
  "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
},
{
  "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "description_highlighted": "...Podcasts About <span class=\"ln-search-highlight\">Television</span>",
  "description_original": "Podcasts About Television",
  "title_highlighted": "Blank Meets Blank",
  "title_original": "Blank Meets Blank",
  "publisher_highlighted": "Shows What You Know",
  "publisher_original": "Shows What You Know",
  "image": "https://production.listennotes.com/podcasts/blank-meets-blank-shows-what-you-know-C9vIq5EA4kr-3FhDrPULIs_.300x300.jpg",
  "thumbnail": "https://production.listennotes.com/podcasts/blank-meets-blank-shows-what-you-know-C9vIq5EA4kr-3FhDrPULIs_.300x300.jpg",
  "itunes_id": 1478435822,
  "latest_pub_date_ms": 1573320376000,
  "earliest_pub_date_ms": 1567181444004,
  "id": "0377b197cb994deb96e7ef4f61755e9c",
  "genre_ids": [
      133,
      111,
      68
  ],
  "listennotes_url": "https://www.listennotes.com/c/0377b197cb994deb96e7ef4f61755e9c/",
  "total_episodes": 5,
  "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "explicit_content": false,
  "website": "http://showswhatyouknow.com/category/blankmeetsblank/?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
  "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
},
{
  "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "description_highlighted": "...Now​ ​adults​ ​with​ ​minds​ ​hopelessly​ ​warped​ ​by​ ​<span class=\"ln-search-highlight\">television</span>,​ ​they’ve​ ​come​ ​together​ ​to​ ​indulge their​ ​shared​ ​obsession.​ ​",
  "description_original": "When​ ​Jon​ ​Gabrus​ ​and​ ​Lauren​ ​Lapkus​ ​were​ ​growing​ ​up,​ ​they​ ​watched​ ​a​ ​lot​ ​of​ ​TV.​ ​Like,​ ​a​ ​LOT​ ​of TV.​ ​Now​ ​adults​ ​with​ ​minds​ ​hopelessly​ ​warped​ ​by​ ​television,​ ​they’ve​ ​come​ ​together​ ​to​ ​indulge their​ ​shared​ ​obsession.​ ​On​ ​Raised​ ​By​ ​TV,​ ​Jon​ ​and​ ​Lauren​ ​revisit​ ​the​ ​best​ ​and​ ​worst​ ​TV​ ​of​ ​the late​ ​80s​ ​and​ ​early​ ​90s​ ​-​ ​everything​ ​from​ ​game​ ​shows​ ​and​ ​TGIF​ ​to​ ​Oprah​ ​and​ ​cereal commercials.&nbsp;",
  "title_highlighted": "Raised by TV",
  "title_original": "Raised by TV",
  "publisher_highlighted": "​Lauren​ ​Lapkus, Jon​ ​Gabrus​, & Earwolf",
  "publisher_original": "​Lauren​ ​Lapkus, Jon​ ​Gabrus​, & Earwolf",
  "image": "https://production.listennotes.com/podcasts/raised-by-tv-lauren-lapkus-jon-gabrus-earwolf-ScwBmdrykI6-8SeJyYw0-nG.300x300.jpg",
  "thumbnail": "https://production.listennotes.com/podcasts/raised-by-tv-lauren-lapkus-jon-gabrus-earwolf-ScwBmdrykI6-8SeJyYw0-nG.300x300.jpg",
  "itunes_id": 1301535199,
  "latest_pub_date_ms": 1571630400000,
  "earliest_pub_date_ms": 1506841200001,
  "id": "d7d68f2372ff406aa42f4fb906915e9d",
  "genre_ids": [
      133
  ],
  "listennotes_url": "https://www.listennotes.com/c/d7d68f2372ff406aa42f4fb906915e9d/",
  "total_episodes": 28,
  "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "explicit_content": true,
  "website": "http://www.earwolf.com/show/raised-by-tv/?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
  "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
},
{
  "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "description_highlighted": "...Podcasts About <span class=\"ln-search-highlight\">Television</span>",
  "description_original": "Podcasts About Television",
  "title_highlighted": "Gilead Gazette - All Things Handmaid's Tale",
  "title_original": "Gilead Gazette - All Things Handmaid's Tale",
  "publisher_highlighted": "Shows What You Know",
  "publisher_original": "Shows What You Know",
  "image": "https://production.listennotes.com/podcasts/gilead-gazette-all-things-handmaids-tale-YaQE8_pv7yb.300x300.jpg",
  "thumbnail": "https://production.listennotes.com/podcasts/gilead-gazette-all-things-handmaids-tale-YaQE8_pv7yb.300x300.jpg",
  "itunes_id": 1376383171,
  "latest_pub_date_ms": 1567181444000,
  "earliest_pub_date_ms": 1496045865018,
  "id": "1893564efd4e4520a1e52de12d6c6679",
  "genre_ids": [
      133,
      69,
      68
  ],
  "listennotes_url": "https://www.listennotes.com/c/1893564efd4e4520a1e52de12d6c6679/",
  "total_episodes": 19,
  "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "explicit_content": false,
  "website": "http://showswhatyouknow.com/category/handmaids/?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
  "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
},
{
  "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "description_highlighted": "...Patrick Beja and Scott Johnson keep you up to date on the important things you need to know about the <span class=\"ln-search-highlight\">video</span> gaming world so you can spend more time playing <span class=\"ln-search-highlight\">games</span>!",
  "description_original": "Patrick Beja and Scott Johnson keep you up to date on the important things you need to know about the video gaming world so you can spend more time playing games!",
  "title_highlighted": "Monthly <span class=\"ln-search-highlight\">Video</span> <span class=\"ln-search-highlight\">Games</span> Briefing",
  "title_original": "Monthly Video Games Briefing",
  "publisher_highlighted": "Daily Tech News Show",
  "publisher_original": "Daily Tech News Show",
  "image": "https://production.listennotes.com/podcasts/monthly-video-games-briefing-daily-tech-q8BawCTnXyA.300x300.jpg",
  "thumbnail": "https://production.listennotes.com/podcasts/monthly-video-games-briefing-daily-tech-q8BawCTnXyA.300x300.jpg",
  "itunes_id": 1438326861,
  "latest_pub_date_ms": 1570564025000,
  "earliest_pub_date_ms": 1534881637014,
  "id": "4475552a8edc49f29edece7529943060",
  "genre_ids": [
      82,
      85
  ],
  "listennotes_url": "https://www.listennotes.com/c/4475552a8edc49f29edece7529943060/",
  "total_episodes": 15,
  "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "explicit_content": false,
  "website": "http://dailytechnewsshow.com/MVGB?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
  "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
},
{
  "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "description_highlighted": "...Are you interested in the since of movies or <span class=\"ln-search-highlight\">video</span> <span class=\"ln-search-highlight\">games</span> or other things? Than come check out discussing <span class=\"ln-search-highlight\">video</span> <span class=\"ln-search-highlight\">games</span> and films.",
  "description_original": "Are you interested in the since of movies or video games or other things? Than come check out discussing video games and films. You can hear about how deadly Mario games are or how impossible quirk moves would work in my hero academia. We also talk about how dumb some things like skeleton ships can be. So strap in and prepare for a ride down sconce lane",
  "title_highlighted": "Discussing <span class=\"ln-search-highlight\">video</span> <span class=\"ln-search-highlight\">games</span> and films",
  "title_original": "Discussing video games and films",
  "publisher_highlighted": "Sophiana the laugh attacker",
  "publisher_original": "Sophiana the laugh attacker",
  "image": "https://production.listennotes.com/podcasts/discussing-video-games-and-films-sophiana-T36m75tNs9z-8joXGCkzgAK.300x300.jpg",
  "thumbnail": "https://production.listennotes.com/podcasts/discussing-video-games-and-films-sophiana-T36m75tNs9z-8joXGCkzgAK.300x300.jpg",
  "itunes_id": 1487173514,
  "latest_pub_date_ms": 1573934651000,
  "earliest_pub_date_ms": 1572916684002,
  "id": "5ee0a4078f4c4e9eb5cc20a55a7c9fa0",
  "genre_ids": [
      204,
      82
  ],
  "listennotes_url": "https://www.listennotes.com/c/5ee0a4078f4c4e9eb5cc20a55a7c9fa0/",
  "total_episodes": 3,
  "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "explicit_content": false,
  "website": "https://anchor.fm/sophie329?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
  "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
},
{
  "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "description_highlighted": "...Pokedex Radio is a fan-made podcast about the Pokemon <span class=\"ln-search-highlight\">video</span> game series. We discuss the mechanics of the <span class=\"ln-search-highlight\">games</span>, give the latest Pokemon related news, and more! Please visit PokedexRadio.com.",
  "description_original": "Learn how to be the very best Pokémon Trainer like no-one ever was! Pokedex Radio is a fan-made podcast about the Pokemon video game series. We discuss the mechanics of the games, give the latest Pokemon related news, and more! Please visit PokedexRadio.com. Send your feedback to Feedback@PokedexRadio.com.",
  "title_highlighted": "Pokedex Radio - a podcast about Pokémon <span class=\"ln-search-highlight\">video</span> <span class=\"ln-search-highlight\">games</span> and news!",
  "title_original": "Pokedex Radio - a podcast about Pokémon video games and news!",
  "publisher_highlighted": "PokedexRadio.com",
  "publisher_original": "PokedexRadio.com",
  "image": "https://production.listennotes.com/podcasts/pokedex-radio-a-podcast-about-pokémon-video-iOQst0kvFMB.300x300.jpg",
  "thumbnail": "https://production.listennotes.com/podcasts/pokedex-radio-a-podcast-about-pokémon-video-iOQst0kvFMB.300x300.jpg",
  "itunes_id": 313551866,
  "latest_pub_date_ms": 1497234154000,
  "earliest_pub_date_ms": 1236368520000,
  "id": "5ab92741ba0d41ca9b8c0c2e1bd20083",
  "genre_ids": [
      85,
      82,
      127,
      131,
      132
  ],
  "listennotes_url": "https://www.listennotes.com/c/5ab92741ba0d41ca9b8c0c2e1bd20083/",
  "total_episodes": 102,
  "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "explicit_content": false,
  "website": "http://pokedexradio.com?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
  "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
},
{
  "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "description_highlighted": "...I talk about <span class=\"ln-search-highlight\">video</span> <span class=\"ln-search-highlight\">games</span> example (Fortnite,nhl,gta) and many more",
  "description_original": "I talk about video games example (Fortnite,nhl,gta) and many more",
  "title_highlighted": "<span class=\"ln-search-highlight\">Video</span> <span class=\"ln-search-highlight\">games</span>",
  "title_original": "Video games ",
  "publisher_highlighted": "Danny Lewis",
  "publisher_original": "Danny Lewis",
  "image": "https://production.listennotes.com/podcasts/video-games-96qI8ztY2wN-1re3LFkJGN8.300x300.jpg",
  "thumbnail": "https://production.listennotes.com/podcasts/video-games-96qI8ztY2wN-1re3LFkJGN8.300x300.jpg",
  "itunes_id": 1494476156,
  "latest_pub_date_ms": 1578629666000,
  "earliest_pub_date_ms": 1578629666000,
  "id": "db221ff8684a4842980d883ab30bd4ae",
  "genre_ids": [
      85,
      82
  ],
  "listennotes_url": "https://www.listennotes.com/c/db221ff8684a4842980d883ab30bd4ae/",
  "total_episodes": 1,
  "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "explicit_content": false,
  "website": "https://anchor.fm/danny-lewis?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
  "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
},
{
  "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "description_highlighted": "...Talking about the esports industry and <span class=\"ln-search-highlight\">video</span> <span class=\"ln-search-highlight\">games</span>",
  "description_original": "Talking about the esports industry and video games",
  "title_highlighted": "<span class=\"ln-search-highlight\">Video</span> <span class=\"ln-search-highlight\">games</span>",
  "title_original": "Video games",
  "publisher_highlighted": "Jackson Harris",
  "publisher_original": "Jackson Harris",
  "image": "https://production.listennotes.com/podcasts/video-games-nG7OE1oY-ru-4e3WGk8Nq2m.300x300.jpg",
  "thumbnail": "https://production.listennotes.com/podcasts/video-games-nG7OE1oY-ru-4e3WGk8Nq2m.300x300.jpg",
  "itunes_id": 1494389035,
  "latest_pub_date_ms": 1578606449000,
  "earliest_pub_date_ms": 1578606449000,
  "id": "3294d88691ac457a9c144aa0c08b8529",
  "genre_ids": [
      82,
      85
  ],
  "listennotes_url": "https://www.listennotes.com/c/3294d88691ac457a9c144aa0c08b8529/",
  "total_episodes": 1,
  "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "explicit_content": false,
  "website": "https://anchor.fm/jackson-harris9?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
  "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
},
{
  "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "description_highlighted": "...<span class=\"ln-search-highlight\">Video</span> <span class=\"ln-search-highlight\">Games</span> Hot Dog is a show in which Zack, Kevin, Riff and Jim talk about <span class=\"ln-search-highlight\">video</span> <span class=\"ln-search-highlight\">games</span>.",
  "description_original": "Video Games Hot Dog is a show in which Zack, Kevin, Riff and Jim talk about video games.",
  "title_highlighted": "<span class=\"ln-search-highlight\">Video</span> <span class=\"ln-search-highlight\">Games</span> Hot Dog",
  "title_original": "Video Games Hot Dog",
  "publisher_highlighted": "Zack, Kevin, Riff and Jim",
  "publisher_original": "Zack, Kevin, Riff and Jim",
  "image": "https://production.listennotes.com/podcasts/video-games-hot-dog-zack-kevin-riff-and-jim-3uiNxVehgXZ.300x300.jpg",
  "thumbnail": "https://production.listennotes.com/podcasts/video-games-hot-dog-zack-kevin-riff-and-jim-3uiNxVehgXZ.300x300.jpg",
  "itunes_id": 431258766,
  "latest_pub_date_ms": 1565769600000,
  "earliest_pub_date_ms": 1366963200281,
  "id": "cc08a8f6be81464ba84fb36d5869ff45",
  "genre_ids": [
      85,
      82,
      133
  ],
  "listennotes_url": "https://www.listennotes.com/c/cc08a8f6be81464ba84fb36d5869ff45/",
  "total_episodes": 282,
  "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "explicit_content": true,
  "website": "http://www.videogameshotdog.com/?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
  "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
},
{
  "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "description_highlighted": "...mike and riley",
  "description_original": "mike and riley",
  "title_highlighted": "<span class=\"ln-search-highlight\">video</span> <span class=\"ln-search-highlight\">games</span>",
  "title_original": "video games",
  "publisher_highlighted": "Riley Davis",
  "publisher_original": "Riley Davis",
  "image": "https://production.listennotes.com/podcasts/video-games-riley-davis-3ounHrG9ywK-hkcgBQAz1T5.300x300.jpg",
  "thumbnail": "https://production.listennotes.com/podcasts/video-games-riley-davis-3ounHrG9ywK-hkcgBQAz1T5.300x300.jpg",
  "itunes_id": 1465916379,
  "latest_pub_date_ms": 1559060620000,
  "earliest_pub_date_ms": 1559060620000,
  "id": "8c4a7a250d184a838daf1082a6e0bcb6",
  "genre_ids": [
      82
  ],
  "listennotes_url": "https://www.listennotes.com/c/8c4a7a250d184a838daf1082a6e0bcb6/",
  "total_episodes": 1,
  "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "explicit_content": false,
  "website": "https://anchor.fm/riley-davis3?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
  "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
},
{
  "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "description_highlighted": "...We are two guys with a passion for <span class=\"ln-search-highlight\">video</span> <span class=\"ln-search-highlight\">games</span> and <span class=\"ln-search-highlight\">video</span> game culture. We're here to talk to you about the latest in all things <span class=\"ln-search-highlight\">video</span> <span class=\"ln-search-highlight\">games</span>.",
  "description_original": "We are two guys with a passion for video games and video game culture. We're here to talk to you about the latest in all things video games.",
  "title_highlighted": "Level Up: <span class=\"ln-search-highlight\">Video</span> <span class=\"ln-search-highlight\">Games</span> Weekly",
  "title_original": "Level Up: Video Games Weekly",
  "publisher_highlighted": "Greg Garand / Cole Jones",
  "publisher_original": "Greg Garand / Cole Jones",
  "image": "https://production.listennotes.com/podcasts/level-up-video-games-weekly-greg-garand-LTBb_Hd0Kli.300x300.jpg",
  "thumbnail": "https://production.listennotes.com/podcasts/level-up-video-games-weekly-greg-garand-LTBb_Hd0Kli.300x300.jpg",
  "itunes_id": 1355457461,
  "latest_pub_date_ms": 1573539045000,
  "earliest_pub_date_ms": 1520121781078,
  "id": "5e6c6b939d774f6c849143c30688951e",
  "genre_ids": [
      82
  ],
  "listennotes_url": "https://www.listennotes.com/c/5e6c6b939d774f6c849143c30688951e/",
  "total_episodes": 80,
  "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "explicit_content": false,
  "website": "https://www.stitcher.com/podcast/level-up-2/level-up-video-games-weekly?refid=stpr&utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
  "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
},
{
  "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "description_highlighted": "...Are <span class=\"ln-search-highlight\">video</span> <span class=\"ln-search-highlight\">games</span> beneficial? \nCover art photo provided by Arturo Rey on Unsplash: https://unsplash.com/@arturorey",
  "description_original": "Are video games beneficial? \nCover art photo provided by Arturo Rey on Unsplash: https://unsplash.com/@arturorey",
  "title_highlighted": "<span class=\"ln-search-highlight\">Video</span> <span class=\"ln-search-highlight\">games</span>",
  "title_original": "Video games ",
  "publisher_highlighted": "Rylie Mussehl",
  "publisher_original": "Rylie Mussehl",
  "image": "https://production.listennotes.com/podcasts/video-games-rylie-mussehl-A5fnyeDG1No-tjxWiZS0c7n.300x300.jpg",
  "thumbnail": "https://production.listennotes.com/podcasts/video-games-rylie-mussehl-A5fnyeDG1No-tjxWiZS0c7n.300x300.jpg",
  "itunes_id": 1449505160,
  "latest_pub_date_ms": 1547495213000,
  "earliest_pub_date_ms": 1547495213000,
  "id": "a9fc6771cd534cc9884e7e4a43bd77a1",
  "genre_ids": [
      82
  ],
  "listennotes_url": "https://www.listennotes.com/c/a9fc6771cd534cc9884e7e4a43bd77a1/",
  "total_episodes": 1,
  "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "explicit_content": false,
  "website": "https://anchor.fm/rylie-mussehl?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
  "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
},
{
  "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "description_highlighted": "...Every Friday, Polygon's Simone de Rochefort, Allegra Frank, and Chelsea Stark talk about what's new and weird in <span class=\"ln-search-highlight\">video</span> <span class=\"ln-search-highlight\">games</span>.",
  "description_original": "Every Friday, Polygon's Simone de Rochefort, Allegra Frank, and Chelsea Stark talk about what's new and weird in video games. Expect goofs, the occasional soft drink-related tirade, and a lot of laughs. Produced by Polygon and the Vox Media Podcast Network.",
  "title_highlighted": "The Polygon Show",
  "title_original": "The Polygon Show",
  "publisher_highlighted": "Polygon",
  "publisher_original": "Polygon",
  "image": "https://production.listennotes.com/podcasts/the-polygon-show-polygon-aw40rP1mpLk-QVzD7e0idFf.300x300.jpg",
  "thumbnail": "https://production.listennotes.com/podcasts/the-polygon-show-polygon-aw40rP1mpLk-QVzD7e0idFf.300x300.jpg",
  "itunes_id": 1245385418,
  "latest_pub_date_ms": 1576234800000,
  "earliest_pub_date_ms": 1496784998135,
  "id": "add2695adf2e4cdcb9389962d6f1eb31",
  "genre_ids": [
      85,
      68,
      82
  ],
  "listennotes_url": "https://www.listennotes.com/c/add2695adf2e4cdcb9389962d6f1eb31/",
  "total_episodes": 136,
  "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "explicit_content": false,
  "website": "https://www.polygon.com/the-polygon-show?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
  "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
},
{
  "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "description_highlighted": "...The Chamber of Secrets \nCover art photo provided by NordWood Themes on Unsplash: https://unsplash.com/@nordwood",
  "description_original": "The Chamber of Secrets \nCover art photo provided by NordWood Themes on Unsplash: https://unsplash.com/@nordwood",
  "title_highlighted": "<span class=\"ln-search-highlight\">Harry</span> <span class=\"ln-search-highlight\">Potter</span>",
  "title_original": "Harry Potter",
  "publisher_highlighted": "Harry Potter",
  "publisher_original": "Harry Potter",
  "image": "https://production.listennotes.com/podcasts/harry-potter-harry-potter-dkQZxf8XU_W-fW3LsEQkNzA.300x300.jpg",
  "thumbnail": "https://production.listennotes.com/podcasts/harry-potter-harry-potter-dkQZxf8XU_W-fW3LsEQkNzA.300x300.jpg",
  "itunes_id": 1441830784,
  "latest_pub_date_ms": 1541786510000,
  "earliest_pub_date_ms": 1541786510000,
  "id": "5cbd1884e7ae46a9b0a857fff104ec6e",
  "genre_ids": [
      104,
      100
  ],
  "listennotes_url": "https://www.listennotes.com/c/5cbd1884e7ae46a9b0a857fff104ec6e/",
  "total_episodes": 1,
  "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "explicit_content": false,
  "website": "https://anchor.fm/farah256?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
  "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
},
{
  "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "description_highlighted": "...This podcast is about <span class=\"ln-search-highlight\">Harry</span> <span class=\"ln-search-highlight\">Potter</span> books. I will read 1 chapter daily. I hope you like it as I am non native English speaker, and trying to improve my voice.",
  "description_original": "This podcast is about Harry Potter books. I will read 1 chapter daily. I hope you like it as I am non native English speaker, and trying to improve my voice. Someone told me, I will speak sweet after 1st book. Let's find out 🙂🤗\n\nP. S. Please inform me wherever I am going wrong, I really want to improve my reading and voice. ",
  "title_highlighted": "<span class=\"ln-search-highlight\">Harry</span> <span class=\"ln-search-highlight\">Potter</span> By Non-Native Speaker",
  "title_original": "Harry Potter By Non-Native Speaker",
  "publisher_highlighted": "Ajinkya Dube",
  "publisher_original": "Ajinkya Dube",
  "image": "https://production.listennotes.com/podcasts/harry-potter-by-non-native-speaker-stdg4ewjQmx-yjPH7EhW4aL.300x300.jpg",
  "thumbnail": "https://production.listennotes.com/podcasts/harry-potter-by-non-native-speaker-stdg4ewjQmx-yjPH7EhW4aL.300x300.jpg",
  "itunes_id": 1480161405,
  "latest_pub_date_ms": 1567972112000,
  "earliest_pub_date_ms": 1567263816003,
  "id": "8f5bf074103f4563a3cbef79777a7884",
  "genre_ids": [
      100,
      104
  ],
  "listennotes_url": "https://www.listennotes.com/c/8f5bf074103f4563a3cbef79777a7884/",
  "total_episodes": 4,
  "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "explicit_content": false,
  "website": "https://anchor.fm/ajinkya-dube?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
  "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
},
{
  "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "description_highlighted": "...<span class=\"ln-search-highlight\">Harry</span> <span class=\"ln-search-highlight\">Potter</span> stuff \nCover art photo provided by Larm Rmah on Unsplash: https://unsplash.com/@larm",
  "description_original": "Harry Potter stuff \nCover art photo provided by Larm Rmah on Unsplash: https://unsplash.com/@larm",
  "title_highlighted": "<span class=\"ln-search-highlight\">Harry</span> <span class=\"ln-search-highlight\">Potter</span>",
  "title_original": "Harry Potter",
  "publisher_highlighted": "Kingsofbob",
  "publisher_original": "Kingsofbob",
  "image": "https://production.listennotes.com/podcasts/harry-potter-kingsofbob-BGQrnp67mxV-BkQwyrqxUcY.300x300.jpg",
  "thumbnail": "https://production.listennotes.com/podcasts/harry-potter-kingsofbob-BGQrnp67mxV-BkQwyrqxUcY.300x300.jpg",
  "itunes_id": 1445455512,
  "latest_pub_date_ms": 1543693949000,
  "earliest_pub_date_ms": 1543693949000,
  "id": "814c68ae3a0646928c1c0135e4e052a7",
  "genre_ids": [
      82
  ],
  "listennotes_url": "https://www.listennotes.com/c/814c68ae3a0646928c1c0135e4e052a7/",
  "total_episodes": 1,
  "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "explicit_content": false,
  "website": "https://anchor.fm/kingsofbob?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
  "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
},
{
  "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "description_highlighted": "...Add a strapline",
  "description_original": "Add a strapline",
  "title_highlighted": "The Tiny Potters | A Kid Led <span class=\"ln-search-highlight\">Harry</span> <span class=\"ln-search-highlight\">Potter</span> Podcast",
  "title_original": "The Tiny Potters | A Kid Led Harry Potter Podcast",
  "publisher_highlighted": "The Tiny Potters | A Kid Led Harry Potter Podcast",
  "publisher_original": "The Tiny Potters | A Kid Led Harry Potter Podcast",
  "image": "https://production.listennotes.com/podcasts/the-tiny-potters-a-kid-led-harry-potter-5xIgHr6XJtP-zr801DOZnYu.300x300.jpg",
  "thumbnail": "https://production.listennotes.com/podcasts/the-tiny-potters-a-kid-led-harry-potter-5xIgHr6XJtP-zr801DOZnYu.300x300.jpg",
  "itunes_id": 1276745230,
  "latest_pub_date_ms": 1531151038000,
  "earliest_pub_date_ms": 1504053070014,
  "id": "622dc01bbe304f79ab826f23e974ed61",
  "genre_ids": [
      100,
      104,
      111,
      114,
      132
  ],
  "listennotes_url": "https://www.listennotes.com/c/622dc01bbe304f79ab826f23e974ed61/",
  "total_episodes": 15,
  "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "explicit_content": false,
  "website": "http://tinypotters.com?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
  "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
},
{
  "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "description_highlighted": "...Honors LA Podcast ",
  "description_original": "Honors LA Podcast ",
  "title_highlighted": "<span class=\"ln-search-highlight\">Harry</span> <span class=\"ln-search-highlight\">Potter</span> 2",
  "title_original": "Harry Potter 2",
  "publisher_highlighted": "Jenna",
  "publisher_original": "Jenna",
  "image": "https://production.listennotes.com/podcasts/harry-potter-2-P9765caKn03-RCqjXnv_3K7.300x300.jpg",
  "thumbnail": "https://production.listennotes.com/podcasts/harry-potter-2-P9765caKn03-RCqjXnv_3K7.300x300.jpg",
  "itunes_id": 1481118462,
  "latest_pub_date_ms": 1569890901000,
  "earliest_pub_date_ms": 1567779911003,
  "id": "c784506cba914ee69021f06a305ad59d",
  "genre_ids": [
      100,
      104
  ],
  "listennotes_url": "https://www.listennotes.com/c/c784506cba914ee69021f06a305ad59d/",
  "total_episodes": 4,
  "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "explicit_content": false,
  "website": "https://anchor.fm/jenna996?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
  "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
},
{
  "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "description_highlighted": "...Rowling, and the <span class=\"ln-search-highlight\">Harry</span> <span class=\"ln-search-highlight\">Potter</span> fandom. Be a part of it—discuss with us on Twitter @NewtCasts.",
  "description_original": "It’s a new era of Harry Potter, and we really, really want to explore it. With 'Cursed Child' and 'Fantastic Beasts' expanding our knowledge of the Wizarding World, we couldn’t resist diving in! A biweekly podcast covering Pottermore, Ilvermorny, J.K. Rowling, and the Harry Potter fandom. Be a part of it—discuss with us on Twitter @NewtCasts.",
  "title_highlighted": "NewtCast: A <span class=\"ln-search-highlight\">Harry</span> <span class=\"ln-search-highlight\">Potter</span> Podcast",
  "title_original": "NewtCast: A Harry Potter Podcast",
  "publisher_highlighted": "Alexis Kaegi",
  "publisher_original": "Alexis Kaegi",
  "image": "https://production.listennotes.com/podcasts/newtcast-a-harry-potter-podcast-alexis-kaegi-0S1CXPic7_q-41mUJ5BiERh.300x300.jpg",
  "thumbnail": "https://production.listennotes.com/podcasts/newtcast-a-harry-potter-podcast-alexis-kaegi-0S1CXPic7_q-41mUJ5BiERh.300x300.jpg",
  "itunes_id": 1139650461,
  "latest_pub_date_ms": 1534367919000,
  "earliest_pub_date_ms": 1470021934016,
  "id": "2ef82acaea134011946338f9169954e2",
  "genre_ids": [
      100,
      104
  ],
  "listennotes_url": "https://www.listennotes.com/c/2ef82acaea134011946338f9169954e2/",
  "total_episodes": 17,
  "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "explicit_content": false,
  "website": "https://anchor.fm/newtcast?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
  "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
},
{
  "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "description_highlighted": "... welcome to my podcast I'm trying my best and I hope you like my episodes",
  "description_original": " welcome to my podcast I'm trying my best and I hope you like my episodes",
  "title_highlighted": "From Hufflepuff House And More <span class=\"ln-search-highlight\">Harry</span> <span class=\"ln-search-highlight\">Potter</span>",
  "title_original": "From Hufflepuff House And More Harry Potter",
  "publisher_highlighted": "iza",
  "publisher_original": "iza",
  "image": "https://production.listennotes.com/podcasts/from-hufflepuff-house-and-more-harry-potter-arbl-yAExk6-zx-mRXZSt5j.300x300.jpg",
  "thumbnail": "https://production.listennotes.com/podcasts/from-hufflepuff-house-and-more-harry-potter-arbl-yAExk6-zx-mRXZSt5j.300x300.jpg",
  "itunes_id": 1436649669,
  "latest_pub_date_ms": 1537296041000,
  "earliest_pub_date_ms": 1537296041000,
  "id": "5dce97dfa6b344249299df397622ffda",
  "genre_ids": [
      132
  ],
  "listennotes_url": "https://www.listennotes.com/c/5dce97dfa6b344249299df397622ffda/",
  "total_episodes": 1,
  "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "explicit_content": false,
  "website": "https://anchor.fm/iza01?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
  "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
},
{
  "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "description_highlighted": "...Danielle and Alison, two sisters with a lifelong love of <span class=\"ln-search-highlight\">Harry</span> <span class=\"ln-search-highlight\">Potter</span>, are rereading the series and talking about what makes J.K. Rowlings' journey through the wizarding world so special.",
  "description_original": "Danielle and Alison, two sisters with a lifelong love of Harry Potter, are rereading the series and talking about what makes J.K. Rowlings' journey through the wizarding world so special. Subscribe and read along with us for the best experience.",
  "title_highlighted": "Weird Sisters <span class=\"ln-search-highlight\">Harry</span> <span class=\"ln-search-highlight\">Potter</span> Reread Podcast",
  "title_original": "Weird Sisters Harry Potter Reread Podcast",
  "publisher_highlighted": "Weird Sisters",
  "publisher_original": "Weird Sisters",
  "image": "https://production.listennotes.com/podcasts/weird-sisters-harry-potter-reread-podcast--ZpGQ18beEB.300x300.jpg",
  "thumbnail": "https://production.listennotes.com/podcasts/weird-sisters-harry-potter-reread-podcast--ZpGQ18beEB.300x300.jpg",
  "itunes_id": 1086413885,
  "latest_pub_date_ms": 1496754014000,
  "earliest_pub_date_ms": 1458606132000,
  "id": "6a679ebefbf947b886e825c65db84080",
  "genre_ids": [
      100,
      104,
      159,
      165
  ],
  "listennotes_url": "https://www.listennotes.com/c/6a679ebefbf947b886e825c65db84080/",
  "total_episodes": 67,
  "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "explicit_content": false,
  "website": "http://weirdsisterspodcast.blogspot.com/?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
  "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
},
{
  "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "description_highlighted": "...We are going to be discussing <span class=\"ln-search-highlight\">Harry</span> <span class=\"ln-search-highlight\">Potter</span> Chapter 2.",
  "description_original": "We are going to be discussing Harry Potter Chapter 2.",
  "title_highlighted": "<span class=\"ln-search-highlight\">Harry</span> <span class=\"ln-search-highlight\">Potter</span>",
  "title_original": "Harry Potter",
  "publisher_highlighted": "Bea Goodman",
  "publisher_original": "Bea Goodman",
  "image": "https://production.listennotes.com/podcasts/harry-potter-DpgWPRAiKlU-kBXmVF75iWJ.300x300.jpg",
  "thumbnail": "https://production.listennotes.com/podcasts/harry-potter-DpgWPRAiKlU-kBXmVF75iWJ.300x300.jpg",
  "itunes_id": 1481118446,
  "latest_pub_date_ms": 1572967064000,
  "earliest_pub_date_ms": 1567779838004,
  "id": "fd1bab113a604bcf8b753f68a40cb5f4",
  "genre_ids": [
      100,
      104
  ],
  "listennotes_url": "https://www.listennotes.com/c/fd1bab113a604bcf8b753f68a40cb5f4/",
  "total_episodes": 5,
  "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "explicit_content": false,
  "website": "https://anchor.fm/bea-goodman?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
  "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
},
{
  "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "description_highlighted": "...ITSS GOOOD",
  "description_original": "ITSS GOOOD",
  "title_highlighted": "<span class=\"ln-search-highlight\">Harry</span> <span class=\"ln-search-highlight\">Potter</span> Podcast",
  "title_original": "Harry Potter Podcast",
  "publisher_highlighted": "Rocco Rohrer",
  "publisher_original": "Rocco Rohrer",
  "image": "https://production.listennotes.com/podcasts/harry-potter-podcast-OfWr-6lyuYV-BMkwpbo1-Od.300x300.jpg",
  "thumbnail": "https://production.listennotes.com/podcasts/harry-potter-podcast-OfWr-6lyuYV-BMkwpbo1-Od.300x300.jpg",
  "itunes_id": 1496382561,
  "latest_pub_date_ms": 1579882855000,
  "earliest_pub_date_ms": 1579882855000,
  "id": "332ce6ea1c434fcc967b5b181d0c61a2",
  "genre_ids": [
      104,
      100
  ],
  "listennotes_url": "https://www.listennotes.com/c/332ce6ea1c434fcc967b5b181d0c61a2/",
  "total_episodes": 1,
  "email": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "explicit_content": false,
  "website": "https://anchor.fm/rocco-rohrer?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
  "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field",
  "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field"
}
];
db.Podcast
  .remove({})
  .then(() => db.Podcast.collection.insertMany(podcastSeed))
  .then(data => {
    console.log(data.result.n + " podcasts included!");
    process.exit(0);
  })
  .catch(err => {
    console.error(err);
    process.exit(1);
  });